/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of:
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int strapdown_ins_propagate(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int strapdown_ins_propagate_alloc_mem(void);
int strapdown_ins_propagate_init_mem(int mem);
void strapdown_ins_propagate_free_mem(int mem);
int strapdown_ins_propagate_checkout(void);
void strapdown_ins_propagate_release(int mem);
void strapdown_ins_propagate_incref(void);
void strapdown_ins_propagate_decref(void);
casadi_int strapdown_ins_propagate_n_in(void);
casadi_int strapdown_ins_propagate_n_out(void);
casadi_real strapdown_ins_propagate_default_in(casadi_int i);
const char* strapdown_ins_propagate_name_in(casadi_int i);
const char* strapdown_ins_propagate_name_out(casadi_int i);
const casadi_int* strapdown_ins_propagate_sparsity_in(casadi_int i);
const casadi_int* strapdown_ins_propagate_sparsity_out(casadi_int i);
int strapdown_ins_propagate_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w);
#define strapdown_ins_propagate_SZ_ARG 5
#define strapdown_ins_propagate_SZ_RES 1
#define strapdown_ins_propagate_SZ_IW 0
#define strapdown_ins_propagate_SZ_W 41
int quat_from_mrp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int quat_from_mrp_alloc_mem(void);
int quat_from_mrp_init_mem(int mem);
void quat_from_mrp_free_mem(int mem);
int quat_from_mrp_checkout(void);
void quat_from_mrp_release(int mem);
void quat_from_mrp_incref(void);
void quat_from_mrp_decref(void);
casadi_int quat_from_mrp_n_in(void);
casadi_int quat_from_mrp_n_out(void);
casadi_real quat_from_mrp_default_in(casadi_int i);
const char* quat_from_mrp_name_in(casadi_int i);
const char* quat_from_mrp_name_out(casadi_int i);
const casadi_int* quat_from_mrp_sparsity_in(casadi_int i);
const casadi_int* quat_from_mrp_sparsity_out(casadi_int i);
int quat_from_mrp_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw, casadi_int* sz_w);
#define quat_from_mrp_SZ_ARG 1
#define quat_from_mrp_SZ_RES 1
#define quat_from_mrp_SZ_IW 0
#define quat_from_mrp_SZ_W 6
#ifdef __cplusplus
} /* extern "C" */
#endif
